CREATE TABLE TABLE_EMAIL (
        EMAIL_ID UUID NOT NULL,
        ATTACH BYTEA,
        EMAIL_FROM VARCHAR(255),
        EMAIL_TO VARCHAR(255),
        OWNER_REF VARCHAR(255),
        SEND_DATE_EMAIL TIMESTAMP(6),
        STATUS_EMAIL VARCHAR(255) CHECK (STATUS_EMAIL IN ('PROCESSING','SENT','ERROR')),
        SUBJECT VARCHAR(255),
        TEXT TEXT,
        PRIMARY KEY (EMAIL_ID)
);

CREATE TABLE TABLE_EMAIL_LOG (
        EMAIL_LOG_ID UUID NOT NULL,
        EMAIL_LOG_DATE TIMESTAMP(6),
        EMAIL_LOG_DESC VARCHAR(255),
        EMAIL_ID UUID,
        PRIMARY KEY (EMAIL_LOG_ID)
);

CREATE TABLE TABLE_USERS (
        ID UUID NOT NULL,
        LOGIN VARCHAR(255),
        PASSWORD VARCHAR(255),
        ROLE VARCHAR(255) CHECK (ROLE IN ('ADMIN','USER')),
        PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS TABLE_EMAIL_LOG
       ADD CONSTRAINT FKD4HWTR2LVFP62TFQ0QQ9LHXSU
       FOREIGN KEY (EMAIL_ID)
       REFERENCES TABLE_EMAIL;